apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground  # Nom du déploiement
  namespace: dev  # Namespace où le déploiement sera créé
spec:
  replicas: 1  # Nombre de réplicas du pod que tu veux avoir
  selector:
    matchLabels:
      app: wil-playground  # Sélecteur pour identifier le pod
  template:
    metadata:
      labels:
        app: wil-playground  # Label pour les pods créés par ce déploiement
    spec:
      containers:
        - name: playground  # Nom du conteneur
          image: wil42/playground:v1 # Ton image Docker (remplace `my-image` par le nom réel de ton image)
          ports:
            - containerPort: 8888 
