apiVersion: v1
kind: Service
metadata:
  name: will-playground
  namespace: dev 
spec:
  selector:
    app: will-playground
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8888 
  type: ClusterIP 

