apiVersion: v1
kind: Service
metadata:
  name: will-playground  # Nom du service
  namespace: dev  # Namespace où le service sera créé
spec:
  selector:
    app: will-playground # Sélection des Pods avec le label "app: pod-playground"
  ports:
    - protocol: TCP
      port: 80  # Le port sur lequel ton Service sera exposé
      targetPort: 8888  # Le port du conteneur auquel le trafic sera redirigé
  type: ClusterIP  # Le type du service, ici un service interne au cluster

